spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect