SELECT * FROM TBL_USER;
select * from user_info;
select * from chargewaiver;
select * from CONFIGS;
select * from chargewaiver where foracid = '02100128311002';
--update chargewaiver set status = 'Y' where foracid = '02100128311002';
--update chargewaiver set status = 'R' where foracid = '01109865841400';
--insert int0 roles (role_id)values role_name = 'ICT_Service_Desk_Maker' where role_id=002';

select * from roles order by role_id asc;
select * from BRANCH;

alter table configs add status number default 1;
commit;

update tbl_user set roleName = 'ICT_Administrator';
update tbl_user set roleName = 'ICT_Service_Desk';
update tbl_user set roleName = 'ICT_Service_Desk_Maker';
update tbl_user set roleName = 'ICT_Service_Desk_Checker';
update tbl_user set roleName = 'Contact_Centre_Officer';
update tbl_user set roleName = 'Branch_Maker';
update tbl_user set roleName = 'Branch_Checker';
update tbl_user set roleName = 'Security_Services_User';
update tbl_user set roleName = 'Head_Office';
commit;

CREATE TABLE "DEPARTMENTS"
(
    "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "NAME" VARCHAR2(50) NOT NULL,
    "DESCRIPTION" VARCHAR2(250) NOT NULL,
    "STATUS" NUMBER NOT NULL,
    "CREATEDBY" VARCHAR2(100) NOT NULL,
    "UPDATEDBY" VARCHAR2(100) NOT NULL,
    "DATECREATED" DATE,
    "DATEUPDATED" DATE,
    CONSTRAINT "DEPARTMENTS_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_DEPARTMENTS_STATUS" FOREIGN KEY ("STATUS") REFERENCES "STATUS"("ID")
);

CREATE TABLE "BRANCH"
(
    "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "NAME" VARCHAR2(50) NOT NULL,
    "DESCRIPTION" VARCHAR2(250) NOT NULL,
    "STATUS" NUMBER NOT NULL,
    "CREATEDBY" VARCHAR2(100) NOT NULL,
    "UPDATEDBY" VARCHAR2(100) NOT NULL,
    "DATECREATED" DATE,
    "DATEUPDATED" DATE,
    CONSTRAINT "BRANCH_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_BRANCH_STATUS" FOREIGN KEY ("STATUS") REFERENCES "STATUS"("ID")
);

CREATE TABLE "MANAGER"
(
    "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "NAME" VARCHAR2(50) NOT NULL,
    "DESCRIPTION" VARCHAR2(250) NOT NULL,
    "DEPARTMENT" NUMBER NOT NULL,
    "STATUS" NUMBER NOT NULL,
    "CREATEDBY" VARCHAR2(100) NOT NULL,
    "UPDATEDBY" VARCHAR2(100) NOT NULL,
    "DATECREATED" DATE,
    "DATEUPDATED" DATE,
    CONSTRAINT "MANAGER_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_MANAGER_DEPARTMENT" FOREIGN KEY ("DEPARTMENT") REFERENCES "DEPARTMENTS"("ID"),
    CONSTRAINT "FK_MANAGER_STATUS" FOREIGN KEY ("STATUS") REFERENCES "STATUS"("ID")
);

CREATE TABLE "LOGCATEGORY"
(
    "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "NAME" VARCHAR2(50) NOT NULL,
    "DESCRIPTION" VARCHAR2(250) NOT NULL,
    "STATUS" NUMBER NOT NULL,
    "CREATEDBY" VARCHAR2(100) NOT NULL,
    "UPDATEDBY" VARCHAR2(100) NOT NULL,
    "DATECREATED" DATE,
    "DATEUPDATED" DATE,
    CONSTRAINT "LOG_CATEGORY_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_LOG_CATEGORY_STATUS" FOREIGN KEY ("STATUS") REFERENCES "STATUS"("ID")
);

CREATE TABLE "ROLE"
(
    "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "NAME" VARCHAR2(50) NOT NULL,
    "DESCRIPTION" VARCHAR2(250) NOT NULL,
    "DEPARTMENT" NUMBER NOT NULL,
    "STATUS" NUMBER NOT NULL,
    "CREATEDBY" VARCHAR2(100) NOT NULL,
    "UPDATEDBY" VARCHAR2(100) NOT NULL,
    "DATECREATED" DATE,
    "DATEUPDATED" DATE,
    CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_DEPARTMENT" FOREIGN KEY ("DEPARTMENT") REFERENCES "DEPARTMENTS"("ID"),
    CONSTRAINT "FK_ROLE_STATUS" FOREIGN KEY ("STATUS") REFERENCES "STATUS"("ID")
);

CREATE TABLE "STATUS"
(	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
     "NAME" VARCHAR2(50) NOT NULL,
     "DESCRIPTION" VARCHAR2(250) NOT NULL,
     CONSTRAINT "STATUS_PK" PRIMARY KEY ("ID"));

insert into STATUS (name, description) values ('ACTIVE','Active resource');
insert into STATUS (name, description) values ('PENDING','Pending resource');
insert into STATUS (name, description) values ('REJECTED','Rejected resource');
insert into STATUS (name, description) values ('INACTIVE','Inactive resource');

insert into DEPARTMENTS (name, description, status, createdby, updatedby, datecreated, dateupdated)
values ('HR','Human Resoure',1,'admin','admin',sysdate,sysdate);
DROP TABLE DEPARTMENTS;
DROP TABLE STATUSES;
commit;